export const tour = {
  slug: "10-days-ecotourism-turkey",
  title: "10 Days Ecotourism Tour Turkey",
  location: "Starts from Istanbul",
  price: 1272,
  originalPrice: 1630,
  rating: 5,
  reviewsCount: 18,
  duration: 10,
  maxGroupSize: 40,
  departureType: "Regular Tour",
  guidingMethod: "Professional Guide",
  language: "English",
  ageRange: "11 - 99",
  images: [
    "https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?w=1200&q=80",
    "https://images.unsplash.com/photo-1524231757912-21f4fe3a7200?w=800&q=80",
    "https://images.unsplash.com/photo-1599940824399-b87987ceb72a?w=800&q=80",
    "https://images.unsplash.com/photo-1527838832700-5059252407fa?w=800&q=80",
  ],
  description:
    "Experience the best of Turkey's natural wonders and historical treasures on this 10-day ecotourism adventure. From the iconic streets of Istanbul to the pristine Seven Lakes, this tour blends cultural immersion with breathtaking nature. Turkey is one of the world's most biologically diverse countries — home to over 9,000 plant species, migratory bird corridors, and ancient forest ecosystems that have survived for millennia. This is not your typical sightseeing package. Every stop on this route has been chosen for its ecological and cultural significance, and every meal celebrates local, seasonal ingredients.\n\nOur expert naturalist guide will walk you through the ecological systems of each region, explaining how geology shaped these landscapes over millions of years. You'll learn about the endemic flora of Yedigoller, the unique cave formations of Ilgarini, the Black Sea's oceanic biodiversity, and the centuries-old Ottoman agricultural traditions still practiced in Safranbolu's villages.\n\nWe keep our groups intentionally small to minimize environmental impact and ensure you get personalized attention. Accommodation is selected for comfort and sustainability — family-run guesthouses where possible, with local staff and farm-to-table dining. This tour is designed for curious, active travelers who want to connect deeply with the places they visit — not just photograph them from a bus window.",
  tags: ["Ecotourism", "Nature", "Culture", "UNESCO", "Caves", "Waterfalls", "Black Sea", "Hiking", "Wildlife", "Small Group", "Family-Friendly", "Photography"],
  highlights: [
    "Istanbul historical sites & Bosphorus Cruise",
    "Seven Lakes (Yedigoller) National Park hike",
    "Abant Lake morning walk & reflection photography",
    "Safranbolu – UNESCO World Heritage town",
    "Ilgarini Cave — one of Turkey's longest cave systems",
    "Ilica Waterfall & natural swimming pools",
    "Amasra medieval castle & Black Sea coastal walk",
    "Kastamonu old city & 14th-century castle",
    "Yenice Forest birdwatching & biodiversity trek",
    "Local farm-to-table meals with seasonal ingredients",
    "Fully guided with professional naturalist",
    "Small group experience (max 40 people)",
    "Expert naturalist commentary at every stop",
    "All national park entrance fees included",
    "Comfortable 4-star hotels throughout",
    "Scenic Black Sea coast drive",
    "Farewell rooftop dinner in Istanbul",
    "Airport transfers both directions",
  ],
  includes: [
    "10 nights hotel accommodation (4-star)",
    "Daily breakfast and dinner",
    "All transportation in air-conditioned vehicle",
    "Professional English-speaking naturalist guide",
    "All entrance fees mentioned in itinerary",
    "Bosphorus cruise ticket",
    "Airport transfer on arrival and departure",
    "Yedigoller National Park guided hike",
    "Ilgarini Cave entrance and guided tour",
    "Ilica Waterfall access",
    "Yenice Forest ranger-led biodiversity walk",
    "Welcome dinner on Day 1",
    "Farewell rooftop dinner on Day 9",
    "Bottled water throughout the tour",
    "Carbon offset contribution",
    "24/7 emergency support from our local team",
    "Digital travel pack with maps, tips & local info",
  ],
  excludes: [
    "International flights",
    "Travel insurance (strongly recommended)",
    "Personal expenses & souvenirs",
    "Lunches (except where noted)",
    "Optional activities not in the itinerary",
    "Visa fees (if applicable)",
    "Alcoholic beverages",
    "Tips for guide and driver (discretionary)",
    "PCR or health tests if required by regulations",
    "Single room supplement (available on request)",
  ],
  itinerary: [
    {
      day: 1,
      title: "Arrival in Istanbul",
      description:
        "Arrive at Istanbul Airport where our guide will meet you with a welcome sign. Transfer by private vehicle to your hotel in the historic Sultanahmet district — walking distance from the Blue Mosque and Hagia Sophia. After settling in, join your fellow travelers for a welcome dinner at a traditional meyhane, where your naturalist guide will walk you through the 10-day journey ahead, covering what to expect, what to wear, and the ecological highlights of each stop. Early bedtime recommended — tomorrow is a big day.",
    },
    {
      day: 2,
      title: "Istanbul City Tour & Bosphorus Cruise",
      description:
        "Start the day at the Blue Mosque (Sultan Ahmed Camii) before the tourist crowds arrive — a quiet moment inside is genuinely moving. Walk across to Hagia Sophia, a 1,500-year-old architectural marvel that has served as cathedral, mosque, and museum. After lunch in a rooftop café with views over the Sea of Marmara, continue to Topkapi Palace and its famous Treasury. Mid-afternoon, explore the covered alleys of the Grand Bazaar — one of the world's oldest shopping malls with over 4,000 shops. End the day with a 90-minute Bosphorus cruise at golden hour, watching the city skyline glow as the call to prayer echoes across the water. Dinner on your own tonight — your guide will recommend neighborhood spots away from tourist traps.",
    },
    {
      day: 3,
      title: "Istanbul → Seven Lakes National Park",
      description:
        "Early departure east toward Bolu province. The drive itself is scenic — you'll cross the Bolu Mountain Pass, a stretch of dense beech and oak forest that turns spectacular in autumn. Arrive at Yedigoller (Seven Lakes) National Park by late morning. The park's seven interconnected lakes are fed by underground springs and surrounded by ancient forest; in spring, the water is an almost unreal turquoise. Your guide will lead a 2–3 hour moderate hike along the forest trail connecting the lakes, explaining the park's unique hydrology, endemic plant species, and the resident otter population. Pack your camera — the reflections are extraordinary. Overnight in Bolu town at a comfortable 4-star hotel.",
    },
    {
      day: 4,
      title: "Abant Lake & UNESCO Safranbolu",
      description:
        "Morning visit to Abant Lake, a volcanic crater lake at 1,328 meters altitude. The 8km lakeside trail is one of Turkey's most peaceful walks — pine and beech forest on one side, the glassy lake on the other. Wildlife here includes foxes, wild boar tracks, and if you're lucky, a glimpse of the rare Eurasian otter. After a lakeside picnic lunch, drive northwest to Safranbolu — a UNESCO World Heritage Site and one of the best-preserved Ottoman towns in the world. The old quarter (Çarşı) is a maze of half-timbered mansions, copper workshops, and the scent of locally grown saffron. Evening guided walk through the bazaar, followed by dinner at a konakevi (mansion-restaurant) with traditional Turkish cuisine.",
    },
    {
      day: 5,
      title: "Safranbolu Depths & Kastamonu",
      description:
        "Spend the morning diving deeper into Safranbolu — visit a restored Ottoman mansion to understand how wealthy merchants lived in the 18th century, browse the weekly bazaar if it's market day, and stop at the local saffron cooperative where you can watch the harvest and processing. After lunch, drive two hours east to Kastamonu, one of Turkey's most undervisited historic cities. The old bazaar district has working copper-smiths, shoe-makers, and spice traders using techniques unchanged for centuries. Climb to the 14th-century Kastamonu Castle for panoramic views over the valley. Overnight in Kastamonu.",
    },
    {
      day: 6,
      title: "Ilgarini Cave & Coastal Amasra",
      description:
        "Today's highlight is Ilgarini Cave — at over 8km in mapped length, it's one of the longest cave systems in Turkey and dramatically less visited than more famous caves. Your guide will lead you through the first 1.5km of accessible galleries, past stalactite formations millions of years in the making, underground streams, and colonies of horseshoe bats roosting in the upper chambers. Helmet and headlamp provided. After emerging blinking into daylight, drive north to Amasra on the Black Sea coast. This ancient Genoese port town sits on a peninsula connected to the mainland by two bridges. The Byzantine and Genoese castle walls are remarkably intact. Dinner of fresh Black Sea fish on the harbor. Overnight in Amasra.",
    },
    {
      day: 7,
      title: "Black Sea Coast: Waterfalls & Wild Swimming",
      description:
        "A full day on one of Turkey's most dramatic and least-touristed coastlines. Morning walk along the Amasra sea walls with views over the Black Sea. Then drive west along the coastal road — a winding, cliff-hugging route with frequent stops at viewpoints. Midday visit to Ilica Waterfall, where a river drops directly into a natural rock pool surrounded by subtropical vegetation. Swimming here is a highlight of the tour — bring your swimwear. Afternoon visit to a small fishing village for a long, leisurely lunch at a family-run lokanta: grilled hamsi (anchovies), fresh bread, and local raki if you fancy. Late afternoon return to the Amasra area. The evening is yours to explore the harbor and its small bars and tea houses.",
    },
    {
      day: 8,
      title: "Yenice Ancient Forest",
      description:
        "Drive inland to Yenice Forest — 20,000 hectares of old-growth broadleaf forest that has been continuously forested since the last ice age. This is a rare thing in Europe or the Middle East: a forest with trees over 500 years old, unlogged, with a full multi-layer canopy structure. Your guide will lead a 4-hour trek on forest trails, focusing on birdwatching (over 170 species recorded here), fungal ecology, and the forest's role in the regional water cycle. Bring binoculars. In spring, wildflower meadows at the forest edges are spectacular. Afternoon free for photography or a second shorter walk. Evening bonfire at the eco-lodge, with a locally sourced dinner and stargazing — light pollution is minimal here.",
    },
    {
      day: 9,
      title: "Return to Istanbul",
      description:
        "A long but beautiful drive back west to Istanbul — your guide will use the journey time for a relaxed Q&A, sharing reading recommendations, conservation organizations to follow, and tips for further travel in Turkey. Arrive in Istanbul by early afternoon. The rest of the day is free: last-minute shopping in the Spice Bazaar, a visit to the Çemberlitaş hammam, or simply wandering the backstreets of Beyoğlu at your own pace. At 7:30pm, meet the group for the farewell dinner at a rooftop restaurant in Galata, with views over the Golden Horn. Toast to ten days well spent.",
    },
    {
      day: 10,
      title: "Departure Day",
      description:
        "Breakfast at the hotel. Your departure transfer will be arranged based on your flight time — let us know your schedule so we can time it perfectly. For those with afternoon or evening flights, your guide can arrange luggage storage and suggest a final morning walk or a last Turkish coffee by the Bosphorus. Safe travels, and we hope to see you on another journey soon.",
    },
  ],
  availability: [
    {
      id: "apr-18",
      startDate: "Apr 18, 2026",
      endDate: "Apr 27, 2026",
      price: 1272,
      spotsLeft: 3,
    },
    {
      id: "may-02",
      startDate: "May 02, 2026",
      endDate: "May 11, 2026",
      price: 1272,
      spotsLeft: 8,
    },
    {
      id: "may-16",
      startDate: "May 16, 2026",
      endDate: "May 25, 2026",
      price: 1350,
      spotsLeft: 20,
    },
    {
      id: "jun-06",
      startDate: "Jun 06, 2026",
      endDate: "Jun 15, 2026",
      price: 1350,
      spotsLeft: 15,
    },
    {
      id: "jun-20",
      startDate: "Jun 20, 2026",
      endDate: "Jun 29, 2026",
      price: 1390,
      spotsLeft: 22,
    },
    {
      id: "jul-04",
      startDate: "Jul 04, 2026",
      endDate: "Jul 13, 2026",
      price: 1420,
      spotsLeft: 18,
    },
    {
      id: "aug-08",
      startDate: "Aug 08, 2026",
      endDate: "Aug 17, 2026",
      price: 1420,
      spotsLeft: 11,
    },
    {
      id: "sep-05",
      startDate: "Sep 05, 2026",
      endDate: "Sep 14, 2026",
      price: 1350,
      spotsLeft: 25,
    },
    {
      id: "sep-19",
      startDate: "Sep 19, 2026",
      endDate: "Sep 28, 2026",
      price: 1350,
      spotsLeft: 30,
    },
    {
      id: "oct-03",
      startDate: "Oct 03, 2026",
      endDate: "Oct 12, 2026",
      price: 1272,
      spotsLeft: 28,
    },
    {
      id: "oct-17",
      startDate: "Oct 17, 2026",
      endDate: "Oct 26, 2026",
      price: 1272,
      spotsLeft: 40,
    },
  ],
  reviews: [
    {
      id: "1",
      name: "Sarah Mitchell",
      avatar: "SM",
      rating: 5,
      date: "March 2026",
      text: "Absolutely incredible experience! The Seven Lakes were breathtaking and our guide was so knowledgeable about Turkish ecology. Safranbolu felt like stepping back in time. Would 100% recommend to anyone who loves nature and history together.",
    },
    {
      id: "2",
      name: "James Okonkwo",
      avatar: "JO",
      rating: 5,
      date: "February 2026",
      text: "The cave visit was the highlight for me — didn't expect it to be so dramatic! Great group size, comfortable hotels, and the food was amazing. Well organized from start to finish. The guide's knowledge of local ecology was genuinely impressive.",
    },
    {
      id: "3",
      name: "Elena Vasquez",
      avatar: "EV",
      rating: 5,
      date: "January 2026",
      text: "I've done maybe 15 guided tours across Europe and Asia and this is easily top three. What makes it special is the off-the-beaten-path routing — you're not fighting crowds anywhere. Yenice Forest on Day 8 felt like we had the entire ancient woodland to ourselves.",
    },
    {
      id: "4",
      name: "Tom Beaumont",
      avatar: "TB",
      rating: 4,
      date: "November 2025",
      text: "Really loved the itinerary and the guide was exceptional. Docking one star only because the Day 7 hotel was slightly below the standard of the rest. That said, the food and experiences more than made up for it. The Ilica Waterfall swimming was a genuine bucket list moment.",
    },
    {
      id: "5",
      name: "Priya Sharma",
      avatar: "PS",
      rating: 5,
      date: "October 2025",
      text: "I booked this solo and was slightly nervous but the group dynamic was wonderful. Mix of ages and nationalities, all with a genuine curiosity about the natural world. The farewell dinner on the Istanbul rooftop was emotional — didn't want it to end.",
    },
    {
      id: "6",
      name: "Marc Lefebvre",
      avatar: "ML",
      rating: 5,
      date: "October 2025",
      text: "As a biologist, I was skeptical that a tour could keep me engaged scientifically. I was wrong. Our naturalist guide had a level of knowledge that would impress a professional audience, and he managed to communicate it accessibly to everyone in the group. The Yenice Forest ecology segment was outstanding.",
    },
    {
      id: "7",
      name: "Anika Müller",
      avatar: "AM",
      rating: 5,
      date: "September 2025",
      text: "The October departure I went on was spectacular — autumn colors at Yedigoller were unreal. I've never taken so many photos on a single trip. Logistics were flawless, every hotel was genuinely nice, and there was not a single moment of 'hurry up and wait.' Highly recommended.",
    },
    {
      id: "8",
      name: "Daniel Park",
      avatar: "DP",
      rating: 4,
      date: "September 2025",
      text: "Great tour overall. The Bosphorus cruise felt a tiny bit rushed given everything else was so generously paced, but that's a minor quibble. Safranbolu and the cave were the standouts for me. Would do this company's other tours without hesitation.",
    },
    {
      id: "9",
      name: "Fatima Al-Hassan",
      avatar: "FA",
      rating: 5,
      date: "August 2025",
      text: "Came with my daughter (age 16) and it was perfect for both of us. She was initially skeptical about a 'nature tour' but by Day 3 she was asking more questions than anyone. The cave day completely captivated her. This tour converts people who don't think they love nature.",
    },
    {
      id: "10",
      name: "Luca Ferretti",
      avatar: "LF",
      rating: 5,
      date: "July 2025",
      text: "The food alone is worth the trip. Every meal felt curated — local produce, dishes I'd never encountered in any Turkish restaurant abroad. The farm-to-table dinner on Day 8 at the eco-lodge was the best meal of my year. And the forest was magnificent.",
    },
    {
      id: "11",
      name: "Rachel Huang",
      avatar: "RH",
      rating: 5,
      date: "June 2025",
      text: "I travel for photography and this tour delivers extraordinary variety in 10 days: Ottoman architecture, ancient forests, Black Sea coast, volcanic lakes, cave formations. Every day offers something totally different. Already planning to come back for the Aegean tour.",
    },
    {
      id: "12",
      name: "Oliver Nkemdirim",
      avatar: "ON",
      rating: 5,
      date: "May 2025",
      text: "What I appreciated most was the pacing. Never rushed, never boring. There was always time to actually sit somewhere beautiful and absorb it rather than just tick it off a list. The guide understood that the best moments aren't always on the itinerary.",
    },
    {
      id: "13",
      name: "Ingrid Sørensen",
      avatar: "IS",
      rating: 4,
      date: "May 2025",
      text: "Excellent tour, very well run. The Black Sea coastal drive is one of the most beautiful roads I've been on. One suggestion: the Kastamonu day could benefit from more free exploration time in the bazaar — we only had about 45 minutes. But overall, a brilliant trip.",
    },
    {
      id: "14",
      name: "Ahmed Khalil",
      avatar: "AK",
      rating: 5,
      date: "April 2025",
      text: "I live in Istanbul and still learned things about my own country on this tour. The naturalist's perspective reframes everything — you stop seeing a forest as a backdrop and start seeing it as a system. Genuinely changed how I think about the landscape I grew up in.",
    },
    {
      id: "15",
      name: "Sofia Bergström",
      avatar: "SB",
      rating: 5,
      date: "April 2025",
      text: "Everything exceeded expectations. The small group size makes such a difference — you can actually talk to your guide, ask follow-up questions, and the group naturally becomes friends. We've already got a WhatsApp group going from our tour.",
    },
    {
      id: "16",
      name: "Kenji Tanaka",
      avatar: "KT",
      rating: 5,
      date: "March 2025",
      text: "Worth every penny. The carbon offset inclusion was a nice touch that aligned with why I chose an ecotourism operator in the first place. Ethical, educational, and genuinely fun. The kind of travel experience that actually expands your worldview.",
    },
    {
      id: "17",
      name: "Claire Dubois",
      avatar: "CD",
      rating: 5,
      date: "November 2024",
      text: "The autumn departure is magical. All those forested hilltops turning gold and red between each destination. The Seven Lakes in mid-autumn are almost absurdly beautiful — like a painting. Book the October date if you can.",
    },
    {
      id: "18",
      name: "George Papandreou",
      avatar: "GP",
      rating: 5,
      date: "October 2024",
      text: "I've been to Turkey four times and this tour showed me corners of the country I had no idea existed. Yenice Forest, Ilgarini Cave, Kastamonu — none of these appear in any mainstream travel guide. That's exactly the point and exactly why this operator is special.",
    },
  ],
};

export const similarTours = [
  {
    slug: "7-days-cappadocia",
    title: "7 Days Cappadocia & Fairy Chimneys",
    duration: 7,
    price: 890,
    originalPrice: 1100,
    image:
      "https://images.unsplash.com/photo-1570939274717-7eda259b50ed?w=600&q=80",
  },
  {
    slug: "12-days-aegean-coast",
    title: "12 Days Turkish Aegean Coast",
    duration: 12,
    price: 1580,
    originalPrice: 1900,
    image:
      "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",
  },
  {
    slug: "5-days-pamukkale",
    title: "5 Days Pamukkale & Hierapolis",
    duration: 5,
    price: 620,
    originalPrice: 780,
    image:
      "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=600&q=80",
  },
  {
    slug: "8-days-black-sea",
    title: "8 Days Black Sea Highlands",
    duration: 8,
    price: 1050,
    originalPrice: 1300,
    image:
      "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",
  },
];
